version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kecapp2019
    ports:
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 3030:8080
